server:  port: 3000  error:    whitelabel:      enabled: false  
spring:  datasource:    username: root    password: pxy123    #password: 123    url: jdbc:mysql://localhost:3306/demo?characterEncoding=UTF-8
  thymeleaf:
    mode: HTML
    encoding: UTF-8    cache: false
    servlet:      content-type: text/html  servlet:    multipart:      max-file-size: 128MB      max-request-size: 128MB  